In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf


In [3]:
path_file = 'G:\\datasets\\shakespeare.txt'

In [4]:
text = open(path_file,'r',encoding="utf8").read()

In [5]:
print(text[500:520])

d buriest thy conten


In [6]:
vocab = sorted(set(text))

In [7]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [8]:
len(vocab)

84

In [9]:
for pair in enumerate(vocab):
    print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [10]:
char_to_ind = {char:ind for ind,char in enumerate(vocab)}

In [11]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [12]:
char_to_ind['H']

33

In [13]:
ind_to_char = np.array(vocab)

In [14]:
ind_to_char[39]

'N'

In [15]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [16]:
encoded_text.shape

(5447699,)

In [17]:
sample = text[:500]

In [18]:
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [19]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [20]:
line = '''From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease'''

In [21]:
len(line)

130

In [22]:
seq_len = 120

In [23]:
total_num_seq = len(text) // (seq_len+1)

In [24]:
total_num_seq

45022

In [25]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [26]:
type(char_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [27]:
sequences = char_dataset.batch(seq_len+1 , drop_remainder=True)

In [28]:
def create_seq_targets(seq):
    input_txt = seq[:-1] #hello my nam
    target_txt = seq[1:] #ello mya name
    return input_txt,target_txt

In [68]:
dataset = sequences.map(create_seq_targets)

In [69]:
for input_txt,target_txt in dataset.take(1):
    print(input_txt.numpy())
    print("".join(ind_to_char[input_txt.numpy()]))
    print("\n")
    print(target_txt.numpy())
    print("".join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [70]:
for i in dataset.take(1):
    print(i)

(<tf.Tensor: shape=(120,), dtype=int32, numpy=
array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75])>, <tf.Tensor: shape=(120,), dtype=int32, numpy=
array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64, 73,
       60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,  1,
       59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,  0,
        1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 5

In [71]:
batch_size = 128

In [72]:
buffer_size = 10000
dataset = dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True)

In [73]:
dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int32, tf.int32)>

In [74]:
for i in dataset.take(1):
    print(i)

(<tf.Tensor: shape=(128, 120), dtype=int32, numpy=
array([[ 1, 27, 73, ..., 75,  1, 78],
       [70, 74, 60, ..., 80, 10,  0],
       [75,  1, 71, ..., 56, 75,  1],
       ...,
       [63, 60,  1, ..., 56, 76, 75],
       [79, 64, 75, ...,  1, 34, 74],
       [ 1, 63, 56, ..., 64, 70, 69]])>, <tf.Tensor: shape=(128, 120), dtype=int32, numpy=
array([[27, 73, 64, ...,  1, 78, 56],
       [74, 60,  1, ..., 10,  0,  1],
       [ 1, 71, 73, ..., 75,  1, 34],
       ...,
       [60,  1, 61, ..., 76, 75, 63],
       [64, 75,  1, ..., 34, 74,  1],
       [63, 56, 77, ..., 70, 69,  1]])>)


In [34]:
vocab_size = len(vocab)

In [35]:
embed_dim = 64

In [36]:
rnn_neurons = 1026

In [37]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [38]:
def sparse_cat_loss(y_true,y_pred):
    return sparse_categorical_crossentropy(y_true,y_pred,from_logits=True)

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,GRU,Dense

In [40]:
def create_model(vocab_size,embed_dim,rnn_neurons,batch_size):
    
    model = Sequential()
    model.add(Embedding(vocab_size,embed_dim,batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons,return_sequences=True,
                 stateful=True,recurrent_initializer='glorot_uniform'))                                                         
    model.add(Dense(vocab_size))
    
    model.compile('adam' ,loss = sparse_cat_loss)
    
    return model

In [62]:
model = create_model(vocab_size= vocab_size,
                     embed_dim = embed_dim,
                     rnn_neurons=rnn_neurons,
                     batch_size=batch_size)
                    

In [63]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (128, None, 64)           5376      
_________________________________________________________________
gru_2 (GRU)                  (128, None, 1026)         3361176   
_________________________________________________________________
dense_2 (Dense)              (128, None, 84)           86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [64]:
for input_example_batch,target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)

In [65]:
for i in dataset.take(1):
    print(i)

(<tf.Tensor: shape=(128, 120), dtype=int32, numpy=
array([[73,  8,  0, ..., 74, 63, 56],
       [74,  1, 80, ..., 75,  8,  0],
       [34, 46, 44, ..., 70, 71, 67],
       ...,
       [74, 60,  1, ...,  2,  0,  1],
       [ 1, 57, 60, ..., 63, 70, 76],
       [74, 75,  1, ..., 62, 73, 70]])>, <tf.Tensor: shape=(128, 120), dtype=int32, numpy=
array([[ 8,  0,  1, ..., 63, 56, 67],
       [ 1, 80, 70, ...,  8,  0,  1],
       [46, 44, 10, ..., 71, 67, 60],
       ...,
       [60,  1, 75, ...,  0,  1,  1],
       [57, 60, 74, ..., 70, 76,  1],
       [75,  1, 64, ..., 73, 70, 78]])>)


In [44]:
input_example_batch

<tf.Tensor: shape=(128, 120), dtype=int32, numpy=
array([[75, 70,  1, ..., 68,  5, 74],
       [70, 61,  1, ..., 62, 56, 77],
       [ 8,  1, 74, ...,  1,  1,  1],
       ...,
       [73, 73, 76, ..., 59,  1, 78],
       [60, 80,  1, ...,  1, 63, 56],
       [68, 80, 74, ...,  2,  1, 34]])>

In [45]:
#example_batch_predictions[0]

In [46]:
sample_indices = tf.random.categorical(example_batch_predictions[0],num_samples=1)

In [47]:
sample_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[69],
       [37],
       [45],
       [81],
       [58],
       [51],
       [27],
       [33],
       [59],
       [ 0],
       [58],
       [25],
       [44],
       [16],
       [52],
       [20],
       [51],
       [64],
       [83],
       [59],
       [77],
       [70],
       [17],
       [17],
       [29],
       [70],
       [15],
       [78],
       [79],
       [69],
       [ 6],
       [50],
       [58],
       [14],
       [38],
       [22],
       [60],
       [61],
       [80],
       [62],
       [39],
       [32],
       [26],
       [23],
       [67],
       [81],
       [22],
       [35],
       [69],
       [64],
       [58],
       [12],
       [28],
       [ 9],
       [14],
       [57],
       [48],
       [37],
       [53],
       [15],
       [24],
       [78],
       [34],
       [82],
       [42],
       [52],
       [32],
       [22],
       [25],
       [80],
       [73],
       [54],
       [41],
   

In [48]:
sample_indices = tf.squeeze(sample_indices,axis=1).numpy()

In [49]:
sample_indices

array([69, 37, 45, 81, 58, 51, 27, 33, 59,  0, 58, 25, 44, 16, 52, 20, 51,
       64, 83, 59, 77, 70, 17, 17, 29, 70, 15, 78, 79, 69,  6, 50, 58, 14,
       38, 22, 60, 61, 80, 62, 39, 32, 26, 23, 67, 81, 22, 35, 69, 64, 58,
       12, 28,  9, 14, 57, 48, 37, 53, 15, 24, 78, 34, 82, 42, 52, 32, 22,
       25, 80, 73, 54, 41, 15, 47, 12, 79, 63,  5, 66, 53,  6, 46, 37, 66,
       55, 25, 45, 33, 67, 74, 83, 57, 42, 58, 50, 67, 42, 11, 83, 19,  6,
       39, 34, 18, 76, 76, 56, 16, 13, 63, 25, 70, 75, 64, 43, 23, 33, 32,
       56], dtype=int64)

In [50]:
epochs = 30

In [51]:
#model.fit(dataset,epochs=epochs)

In [52]:
from tensorflow.keras.models import load_model

In [53]:
model = create_model(vocab_size,embed_dim,rnn_neurons,batch_size=1)

model.load_weights('shakespear_model.h5')

model.build(tf.TensorShape([1,None]))

In [54]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (1, None, 64)             5376      
_________________________________________________________________
gru_1 (GRU)                  (1, None, 1026)           3361176   
_________________________________________________________________
dense_1 (Dense)              (1, None, 84)             86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [55]:
def generate_text(model,start_seed,gen_size=500,temp=1.0):
    num_generate = gen_size
    
    input_eval = [char_to_ind[s] for s in start_seed]
    
    input_eval = tf.expand_dims(input_eval,0)
    
    text_generated = []
    
    temperature = temp
    
    model.reset_states()
    
    for i in range(num_generate):
        predictions = model(input_eval)
        
        predictions = tf.squeeze(predictions,0)
        
        predictions = predictions/temperature
        
        predictions_id = tf.random.categorical(predictions,num_samples=1)[-1,0].numpy()
        
        input_eval = tf.expand_dims([predictions_id],0)
        
        text_generated.append(ind_to_char[predictions_id])
        
    return (start_seed + "".join(text_generated))

In [56]:
print(generate_text(model,"mitra",gen_size=1000))


mitrance;
    Bear! Where's my consext, 'the gentleman here?
DROMIO OF EPHESUS. Patience, good madam.
    How long have  well shall be forsworn.
    O this allain and mistress hast thou bark'st.
    That shall I bring thee that that did the Duke,
    Rescae Edmund? Let thy virtue love in my
    kinsme, 'twas Suffolk's house; let the trumpet; therefore, 'tis Tribute, the King's, and
    that thou seem our poison in his hand, I am a time
    Do there where ease myself so easily as
    Warwick, although she thence,
    As is thy tongue and will, and wept to-
    His eyes do hare the heir of unconstant death,
    And live-cheat, set it thus, and this shall be proud;
    I name not one of our master.
  LAUNCE. If the deceive not desire it too much clapp'd from death.          Exit  
  LOUNCES. Here is my hand, sir; she is working for the child, horte poisons.
    My lord, welcome, sir; the nois me this last cause
    To give her to my foes, so again,
  I keep perfecteth that sanct unto the 

In [57]:
#from keras.models import load_model

In [58]:
#model.save('shakespear_model.h5')